import "./globals.css";
import Footer from '../Components/Footer.jsx'

export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
